BELLSYSD.FRM
C:\WINDOWS\SYSTEM\MCI.VBX
C:\WINDOWS\SYSTEM\THREED.VBX
C:\WINDOWS\SYSTEM\SPIN.VBX
C:\WINDOWS\SYSTEM\CMDIALOG.VBX
BELLSYSD.BAS
C:\WINDOWS\SYSTEM\GRID.VBX
ProjWinSize=68,392,248,270
ProjWinShow=2
IconForm="frmMain"
Title="BELL SYSTEM DEMO VERSION"
ExeName="BELLSYSD.EXE"
Path="..\EXEFILES"
